// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovDLmckY3eUVt1v-Ve8rvrqFWGgTuKNc',
    appId: '1:224079958717:web:dc6fcf2c89d690559addd4',
    messagingSenderId: '224079958717',
    projectId: 'fir-auth-21d25',
    authDomain: 'fir-auth-21d25.firebaseapp.com',
    storageBucket: 'fir-auth-21d25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VOGnNx1z8kpFsC3TMR4o1CxOukAlZts',
    appId: '1:224079958717:android:e45dc8bcc9caea869addd4',
    messagingSenderId: '224079958717',
    projectId: 'fir-auth-21d25',
    storageBucket: 'fir-auth-21d25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdLJfKbxcOxu9Uy0jdbpuge0ZLR25HBo',
    appId: '1:224079958717:ios:300101f568af597b9addd4',
    messagingSenderId: '224079958717',
    projectId: 'fir-auth-21d25',
    storageBucket: 'fir-auth-21d25.firebasestorage.app',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdLJfKbxcOxu9Uy0jdbpuge0ZLR25HBo',
    appId: '1:224079958717:ios:300101f568af597b9addd4',
    messagingSenderId: '224079958717',
    projectId: 'fir-auth-21d25',
    storageBucket: 'fir-auth-21d25.firebasestorage.app',
    iosBundleId: 'com.example.googleSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDovDLmckY3eUVt1v-Ve8rvrqFWGgTuKNc',
    appId: '1:224079958717:web:3416252f644813409addd4',
    messagingSenderId: '224079958717',
    projectId: 'fir-auth-21d25',
    authDomain: 'fir-auth-21d25.firebaseapp.com',
    storageBucket: 'fir-auth-21d25.firebasestorage.app',
  );
}
